FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /app
COPY DotNetTestApp.csproj ./
COPY *.cs ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-runtime AS runtime
WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "DotNetTestApp.dll"]